### ISSUE TITLE
setup.py fails to compile if Raysect and Cherab are not present

### ISSUE THREAD

**Issue by vitaproject** [vitaproject/core#10]
Both packages should be optional. Is it possible to add a check within setup.py so that if they're not found the setup.py does not fail?

**Comment by mattngc** [comment]
Fixed this by making the CHERAB extensions optional in the setup.py. Now can be installed with

`python setup.py develop --include-cherab`

Extensions can be rebuilt with

$~>dev/build.sh --include-cherab
