### ISSUE TITLE
Fork Raysect

### ISSUE THREAD

**Issue by daniel-iglesias** [vitaproject/core#40]
Until the next release of Raysect, we are using features that are still to be merged into the master branch. Can it be forked temporarily within vitaproject?

**Comment by CnlPepper** [comment]
There is no need to fork it, just refer to a specific commit hash for the version you are using. The history is stable on github so it won't be going anywhere.

**Comment by CnlPepper** [comment]
I'm hoping to fold in one more feature related to the function framework, then we'll be making another release.

**Comment by CnlPepper** [comment]
Ah no, ignore this. Matt just made me aware it's code in a customised branch. That will need a fork.

**Comment by mattngc** [comment]
Steps for resolution:

1. Fork raysect into vita project group
2. Merge the changes from the custom mesh_triangle_intersection branch into the forked master.
3. Delete the original mesh_triangle_intersection branch on Raysect.
4. Append '-vita1' to the version number in raysect.core so there will be no confusion when it is installed.
5. Pull changes to master as and when they are released, until Version 1.0 is available. At which point the fork is presumably no longer required.

**Comment by mattngc** [comment]
Completed
