### ISSUE TITLE
Github actions and CI suggestions

### ISSUE THREAD

**Issue by CnlPepper** [vitaproject/core#42]
@daniel-iglesias I noticed you are expanding the development workflow for the project and setting up CI. I had a quick look through and can I make the following suggestions:

Before moving any further with the CI I think you should consider restructuring the project to reduce risks to the project from a CI configuration mistake. I see some effort has started down this path by splitting off the actions branch, however this is probably not the ideal solution.

I recommend you start by implementing a simplified git-flow style workflow. Here you have master, development and feature/bugfix branches.

* master holds a stable, guaranteed working copy of the code
* development is were new features are added and merged, not always guaranteed to be functional
* feature/* and bugfix/* branches are where new developments are created

Only the repo admin should be able to push to master, any other change is only permitted though a merge request from development or, if critical, a bugfix branch that is also merged into development.

Only the core developers should have access to push directly to development (for dealing with clashes and minor issues). All other, larger changes, are developed in feature/* branches and merged (pull request) into development at appropriate points.

Feature and bug fix branches are transient and only exist for the development time of a feature. They are destroyed and recreated as required.

With this in place, the CI can then be configured to run when pull requests are generated. This will prevent endless (and mostly pointless) series of documentation and test runs. You could leave automated testing on for commits, but developers should be running them locally and it only matters that the code is passing tests before the pull into development and master.

This configuration would also prevent a private change to the CI disrupting the project, by limiting any damage to a side branch.

One note on the current actions implementation: I strongly recommend the commit code is modified to add a commit message that links the autogenerated commits to the commit they derive from: "Generated documentation for commit #abcdef.". This would be easier if the git command is used directly to perform the commit in vita.yml. Both the doc and out folders can be committed in a single operation, using something like:

```
git add out/*
git add doc/*
git commit -m $COMMIT_MESSAGE
git push
```

**Comment by mattngc** [comment]
There is a nice article on the git-flow workflow Alex mentions here (https://nvie.com/posts/a-successful-git-branching-model/). The diagrams help alot.

You can also see how it is used in practice on the Raysect and Cherab git repos.

**Comment by daniel-iglesias** [comment]
Yes, very good guides and comments. I've created the develop branch, so let's all use this now on except for major releases.

**Comment by mattngc** [comment]
Changes implemented.
